language: cpp
dist: trusty
sudo: false
os: linux
compiler: gcc-7
notifications:
  email: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kubuntu-backports
    packages:
      - g++-7

cache:
  directories:
    - build

install:
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
  - mkdir -p "${TRAVIS_BUILD_DIR}/build"

# Incremental builds script from:
# https://blog.esciencecenter.nl/travis-caching-and-incremental-builds-6518b89ee889
# https://github.com/roofit-dev/root/blob/2cc63b8b3d0a7c3acca4381e1bc5a7ef3e01a94c/.travis.yml
script:
  - make -j2

