language: cpp
os: linux
notifications:
  email: true
python:
    - "3.4"

addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.5
      - python3-pip

cache:
  directories:
    - build

before_install:
    - pip3 install --user pytest

install:
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
  - mkdir -p "${TRAVIS_BUILD_DIR}/build"

script:
  - make -j2
  - python3 -m pytest

